### PR TITLE
fix import/include

### PR DESCRIPTION
**Pull request by NatalieEO**
dockstore/dockstore#3349
Need to add $ to fix tests for this PR https://github.com/dockstore/dockstore/pull/3794

### CODE REVIEW

**Review by denis-yuen — APPROVED** [review]

**Comment by denis-yuen** [comment]
FYI, this seems like it would insta-break other builds. So only merge after merging dockstore/dockstore#3794 and let other people know to update from develop

**Comment by NatalieEO** [comment]
> FYI, this seems like it would insta-break other builds. So only merge after merging [dockstore/dockstore#3794](https://github.com/dockstore/dockstore/pull/3794) and let other people know to update from develop

I can only merge the other PR when this is merged, otherwise the tests will fail. Unless I consider `$import` and `import` valid like @coverbeck suggested, then I won't have to change repo. The other option is merging this to a new branch, and change the tests in my other PR to reference the new branch.

On another note, this cwl is invalid in general before and after adding `$` to the imports.

**Comment by garyluu** [comment]
> > FYI, this seems like it would insta-break other builds. So only merge after merging [dockstore/dockstore#3794](https://github.com/dockstore/dockstore/pull/3794) and let other people know to update from develop
> 
> I can only merge the other PR when this is merged, otherwise the tests will fail. Unless I consider `$import` and `import` valid like @coverbeck suggested, then I won't have to change repo. The other option is merging this to a new branch, and change the tests in my other PR to reference the new branch.
> 
> On another note, this cwl is invalid in general before and after adding `$` to the imports.

We're actually not supposed to use the master branch in tests, you should use a tagged version

**Review by garyluu — APPROVED** [review]

**Comment by NatalieEO** [comment]
> > > FYI, this seems like it would insta-break other builds. So only merge after merging [dockstore/dockstore#3794](https://github.com/dockstore/dockstore/pull/3794) and let other people know to update from develop
> > 
> > 
> > I can only merge the other PR when this is merged, otherwise the tests will fail. Unless I consider `$import` and `import` valid like @coverbeck suggested, then I won't have to change repo. The other option is merging this to a new branch, and change the tests in my other PR to reference the new branch.
> > On another note, this cwl is invalid in general before and after adding `$` to the imports.
> 
> We're actually not supposed to use the master branch in tests, you should use a tagged version

Okay, I made a ticket dockstore/dockstore#3802. For now I made a new branch to merge this PR into and I'll make a tagged release off of that branch and use that in the tests. The tests that use it now all use master

**Review by coverbeck — APPROVED** [review]

**Pull request merged**
